package org.poc.telegrambot.bot.users.entities;

public enum States {
    EXIT,
    START,
    MEMBERS_ALL,
    MEMBERS_BY_EMAIL,
    MERGE_REQUESTS_ALL,
    MERGE_REQUESTS_BY_FILTER,
    MERGE_REQUEST_BY_IID,
    BRANCHES_ALL,
    BRANCH_BY_NAME,
    COMMITS_BY_BRANCH_NAME_AND_FILTER,
    COMMITS_BY_BRANCH_NAME,
    COMMITS_BY_MR_IID_AND_FILTER,
    COMMITS_BY_MR_IID,
    EMAIL_FILTER,
    SINCE_FILTER,
    UNTIL_FILTER,
    BRANCH_FILTER,
    MERGE_REQUEST_FILTER
}
